Testing exercise 2
Edinson29/Ruby-exercises pull request #2
Opened 2019-07-12 22:29 UTC by Edinson29

Here I leave the exercise number 2

2019-07-12 22:45 UTC, danielosorio83 requested changes

2019-07-12 22:45 UTC, danielosorio83 commented on even_fibonacci_numbers.rb
> +def fibonacci
te recomiendo recibir un parametro en la funcion, y usar el parametro para el tope del ciclo... osea que a la funcion le pases los 4 m'.. para q la funcion se pueda reutilizar

2019-07-12 22:45 UTC, danielosorio83 commented on even_fibonacci_numbers.rb
> +	elsif c >= 4_000_000
para que es esta condicion?

2019-07-12 22:46 UTC, danielosorio83 commented
@Edinson29 el commit del cambio del tab no ajusto todas las lineas

2019-07-12 22:52 UTC, Edinson29 commented on even_fibonacci_numbers.rb
> +	elsif c >= 4_000_000
Esa condicion es la que no deja que imprima un numero por encima de la condicion dada y los restaura a su valor anterior, porque el ciclo while se sale cuando el limite es mayor pero deja que se impriman las variables que lo superaron

2019-07-12 23:13 UTC, danielosorio83 requested changes

2019-07-12 23:13 UTC, danielosorio83 commented on even_fibonacci_numbers.rb
> +def fibonacci(limit = 4_000_000)
es necesario colocar el default al parametro, la idea es que el valor del limite se lo pases por parametro.. para que llames
`fibonacci(4_000_000)`

2019-07-12 23:13 UTC, danielosorio83 commented on even_fibonacci_numbers.rb
> +	elsif c >= limit
sigo sin entender esta condicion aqui, para que la usas? osea cual es el proposito de el codigo interno... lo q entiendo es que cuando pase el limite devuelva `c` a su valor anterior... pero para q?

2019-07-15 14:55 UTC, danielosorio83 approved these changes

2019-07-15 14:55 UTC, merged