List number 10001 prime
Edinson29/Ruby-exercises pull request #8
Opened 2019-07-18 20:14 UTC by Edinson29

2019-07-18 20:56 UTC, danielosorio83 requested changes

2019-07-18 20:56 UTC, danielosorio83 commented on palindromo.rb
> +# Create a method that receives a word and returns whether it is a palindrom or not
este archivo tampoco va aqui

2019-07-18 20:56 UTC, danielosorio83 commented on 10001st_prime.rb
> +  Prime.first(prime)
esto es trampa... la idea es q lo encuentre sin la ayuda de librerias q ya lo hacen

2019-07-19 19:32 UTC, Edinson29 commented
Fue cerrado porque tenia un commit que no iba ahi

2019-07-19 19:32 UTC, closed without merging